version: '3.9'
services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - database
  database:
    image: postgres
    environment:
      POSTGRES_USER: victor99dev
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: product-db
    ports:
      - 5432:5432
